version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "24678:24678"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: pnpm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
    environment:
      - GO_ENV=development
    command: air -c .air.toml

